### ISSUE TITLE
Compilation Failure

### ISSUE THREAD

**Issue by sasdallas** [vladcc/Tetris-OS#3]
Hello, I believe this is a bug:

When I try to compile your OS using make(gcc, ld, etc are installed), it gives an error:
```
drivers/interrupts.c: Assembler messages:
drivers/interrupts.c:71: Error: `pusha' is not supported in 64-bit mode
drivers/interrupts.c:78: Error: `popa' is not supported in 64-bit mode
```

This is not just on `interrupts.c`, it's on almost all of the drivers.
Is this a bug or is something wrong with my system?

P.S. There may be another bug, I tried to remove all instances(just to get it to compile) of `pusha` and `popa`, and it failed on the `ld` step with the error: `ld: i386 architecture of input file 'boot/k_entry.o' is incompatible with i386:x86-64 output`.

**Comment by sasdallas** [comment]
For the P.S., I'm quite sure the reason is due to you doing `-f elf` on NASM instead of `-f elf32`

**Comment by vladcc** [comment]
Hi Samuel!
Yup, looks like you are assembling for 64 bit.
That's way too many bits for this project :)

**Comment by sasdallas** [comment]
I

> Hi Samuel!
> Yup, looks like you are assembling for 64 bit.
> That's way too many bits for this project :)

If that’s the case, is there something wrong with os.make? I used your directions and files.

**Comment by vladcc** [comment]
I suspect I was originally using a 32 bit version of nasm, so it compiled to 32 bit by default. A 64 bit version would probably require you to specify you want a 32 bit binary.

**Comment by sasdallas** [comment]
It's been about 2 years now, cleaning up my github profile and looking at this with stupidity haha. Thanks for your help!

**Comment by sasdallas** [comment]
For reference, to fix this you will need to edit os.make to use `-f elf32` instead.
